"""add canvas positions and goal contributions

Revision ID: 169f0923505f
Revises: a0df57eef953
Create Date: 2026-07-11 17:18:10.576397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '169f0923505f'
down_revision: Union[str, None] = 'a0df57eef953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('payout_period_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['payout_period_id'], ['payout_periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channels', sa.Column('canvas_x', sa.Float(), nullable=True))
    op.add_column('channels', sa.Column('canvas_y', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('canvas_x', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('canvas_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'canvas_y')
    op.drop_column('goals', 'canvas_x')
    op.drop_column('channels', 'canvas_y')
    op.drop_column('channels', 'canvas_x')
    op.drop_table('goal_contributions')
    # ### end Alembic commands ###
