"""add expense due_day

Revision ID: 675bc76494c0
Revises: bb7876a0bece
Create Date: 2026-08-16 07:54:19.722200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '675bc76494c0'
down_revision: Union[str, None] = 'bb7876a0bece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('due_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'due_day')
    # ### end Alembic commands ###
