"""add channel funding source

Revision ID: 6c5ff0f03528
Revises: 0001
Create Date: 2026-07-06 20:34:12.459971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c5ff0f03528'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('funding_source_channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channels', 'channels', ['funding_source_channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'funding_source_channel_id')
    # ### end Alembic commands ###
