"""add goal channel and round up

Revision ID: 8ff13437c567
Revises: 6c5ff0f03528
Create Date: 2026-07-06 21:09:10.267622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ff13437c567'
down_revision: Union[str, None] = '6c5ff0f03528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.add_column(
        'goals',
        sa.Column('round_up_to_hundred', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_foreign_key(None, 'goals', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'round_up_to_hundred')
    op.drop_column('goals', 'channel_id')
    # ### end Alembic commands ###
