"""add users table and user_id ownership columns

Revision ID: a0df57eef953
Revises: d2b3c4e5f6a7
Create Date: 2026-07-11 16:18:16.898030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0df57eef953'
down_revision: Union[str, None] = 'd2b3c4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('assets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'users', ['user_id'], ['id'])
    op.add_column('channels', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('channels_name_key', 'channels', type_='unique')
    op.create_unique_constraint(None, 'channels', ['user_id', 'name'])
    op.create_foreign_key(None, 'channels', 'users', ['user_id'], ['id'])
    op.add_column('credit_lines', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'credit_lines', 'users', ['user_id'], ['id'])
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    op.add_column('goals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goals', 'users', ['user_id'], ['id'])
    op.add_column('payout_periods', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('payout_periods_label_key', 'payout_periods', type_='unique')
    op.create_unique_constraint(None, 'payout_periods', ['user_id', 'label'])
    op.create_foreign_key(None, 'payout_periods', 'users', ['user_id'], ['id'])
    op.add_column('transfers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'user_id')
    op.drop_constraint(None, 'payout_periods', type_='foreignkey')
    op.drop_constraint(None, 'payout_periods', type_='unique')
    op.create_unique_constraint('payout_periods_label_key', 'payout_periods', ['label'], postgresql_nulls_not_distinct=False)
    op.drop_column('payout_periods', 'user_id')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_column('goals', 'user_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'user_id')
    op.drop_constraint(None, 'credit_lines', type_='foreignkey')
    op.drop_column('credit_lines', 'user_id')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='unique')
    op.create_unique_constraint('channels_name_key', 'channels', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('channels', 'user_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
