"""remove channel funding source

Revision ID: bafc51ed3cb6
Revises: 70eb279d1034
Create Date: 2026-07-12 17:03:22.109427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bafc51ed3cb6'
down_revision: Union[str, None] = '70eb279d1034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_funding_source_channel_id_fkey', 'channels', type_='foreignkey')
    op.drop_column('channels', 'funding_source_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('funding_source_channel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('channels_funding_source_channel_id_fkey', 'channels', 'channels', ['funding_source_channel_id'], ['id'])
    # ### end Alembic commands ###
