"""add onboarding completed at

Revision ID: f41911fb2fea
Revises: f4b39bfa1521
Create Date: 2026-08-02 00:47:49.125538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f41911fb2fea'
down_revision: Union[str, None] = 'f4b39bfa1521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Backfill: any user who already has at least one channel is clearly
    # already using the app, not a brand-new account -- mark onboarding
    # complete for them so they never see the setup banner. Users with zero
    # channels (new, or pre-existing but never actually started) are left
    # NULL and will see onboarding on their next visit, which is correct
    # for both cases.
    op.execute(
        """
        UPDATE users
        SET onboarding_completed_at = now()
        WHERE id IN (SELECT DISTINCT user_id FROM channels WHERE user_id IS NOT NULL)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    # ### end Alembic commands ###
